name: Make My APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Files
      uses: actions/checkout@v4

    - name: Set up Java Compiler Environment
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Move Assets Into App Folder
      run: |
        mkdir -p app/src/main/assets
        rsync -av . app/src/main/assets/ --exclude app --exclude .git --exclude .github

    - name: Compile Website to APK File
      uses: elvisjacob/website-to-apk-action@v1.0.2
      with:
        app-name: "TreeOfGames"
        build-folder-path: "./"
        output-folder-path: "output/"

    - name: Upload Final Android App Package
      uses: actions/upload-artifact@v4
      with:
        name: My-Phone-App
        path: output/**/*.apk
